name: codec-harness-env
channels:
  - conda-forge
  - pytorch
  - nvidia # For CUDA toolkit
dependencies:
  - python=3.10
  - ffmpeg
  - pip
  - pytorch
  - torchvision
  - torchaudio
  - pytorch-cuda=11.8 # Or match to your system
  - pip:
    - -e .
    - pytorch-msssim
    - tqdm
    # Add other pip dependencies from DCVC/HiNeRV